version: '3.0'
services:
  mailpile_dev:
    container_name: mailpile_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: mailpile_dev
    volumes:
      - .:/Mailpile
      - .dev-mailpile-data:/mailpile-data:rw
    ports:
      - 33411:33411

